name: Build 1.52.7 Dylib FINAL

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Theos v1.4
      uses: Randomblock1/theos-action@v1
      with:
        theos-dir: theos
        orion: false

    - name: Build Package
      run: make package FINALPACKAGE=1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: CriticalOpsWin-1.52.7
        path: packages/*.dylib
